server:
  port: 8084

api:
  bc_crypto_coingecko:
    domain: localhost:8082/crypto/coingecko/api/v1
    endpoints:
      currency: usd
      coinList: coinList
      market: market
  bc_stock_finnhub:
    domain: localhost:8083/stock/finnhub/api/v1
    endpoint:
      quote: quote
      profile: profile2
      stockList: stockList

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bc2311
    username: "postgres"
    password: "admin1234"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop # update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: bc2311
        jdbc:
          time_zone: UTC
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
